config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :user_needs

      resources :comments

      resources :course_ratings

      resources :quarters

      resources :course_offerings

      resources :professors

      resources :courses

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "courses#index"
  resources :user_needs
  resources :comments
  resources :course_ratings
  resources :quarters
  resources :course_offerings
  resources :professors
  resources :courses
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/quarter.rb
class Quarter < ApplicationRecord
  # Direct associations

  has_many   :course_offerings,
             dependent: :destroy

  # Indirect associations

  has_many   :courses,
             through: :course_offerings,
             source: :course

  # Validations

  # Scopes

  def to_s
    season
  end
end

app/controllers/api/v1/quarters_controller.rb
class Api::V1::QuartersController < Api::V1::GraphitiController
  def index
    quarters = QuarterResource.all(params)
    respond_with(quarters)
  end

  def show
    quarter = QuarterResource.find(params)
    respond_with(quarter)
  end

  def create
    quarter = QuarterResource.build(params)

    if quarter.save
      render jsonapi: quarter, status: :created
    else
      render jsonapi_errors: quarter
    end
  end

  def update
    quarter = QuarterResource.find(params)

    if quarter.update_attributes
      render jsonapi: quarter
    else
      render jsonapi_errors: quarter
    end
  end

  def destroy
    quarter = QuarterResource.find(params)

    if quarter.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: quarter
    end
  end
end

app/controllers/quarters_controller.rb
class QuartersController < ApplicationController
  before_action :set_quarter, only: %i[show edit update destroy]

  def index
    @q = Quarter.ransack(params[:q])
    @quarters = @q.result(distinct: true).includes(:course_offerings,
                                                   :courses).page(params[:page]).per(10)
  end

  def show
    @course_offering = CourseOffering.new
  end

  def new
    @quarter = Quarter.new
  end

  def edit; end

  def create
    @quarter = Quarter.new(quarter_params)

    if @quarter.save
      redirect_to @quarter, notice: "Quarter was successfully created."
    else
      render :new
    end
  end

  def update
    if @quarter.update(quarter_params)
      redirect_to @quarter, notice: "Quarter was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @quarter.destroy
    redirect_to quarters_url, notice: "Quarter was successfully destroyed."
  end

  private

  def set_quarter
    @quarter = Quarter.find(params[:id])
  end

  def quarter_params
    params.require(:quarter).permit(:season, :year)
  end
end

app/views/quarters/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Quarter #<%= quarter.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Season</dt>
      <dd><%= quarter.season %></dd>

      <dt>Year</dt>
      <dd><%= quarter.year %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back quarter, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_quarter_url(quarter), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to quarter, method: :delete, data: { confirm: "Do you really want to delete this quarter?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(quarter.updated_at) %> ago
  </div>
</div>

app/views/quarters/_form.html.erb
<% was_validated = quarter.errors.any? %>

<%= form_with(model: quarter, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% season_class = "form-control" %>
    <% season_was_invalid = quarter.errors.include?(:season) %>

    <% if was_validated %>
      <% if season_was_invalid %>
        <% season_class << " is-invalid" %>
      <% else %>
        <% season_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :season %>
    <%= f.text_field :season, class: season_class, placeholder: "Enter season" %>
    <% if season_was_invalid %>
      <% quarter.errors.full_messages_for(:season).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% year_class = "form-control" %>
    <% year_was_invalid = quarter.errors.include?(:year) %>

    <% if was_validated %>
      <% if year_was_invalid %>
        <% year_class << " is-invalid" %>
      <% else %>
        <% year_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :year %>
    <%= f.number_field :year, class: year_class, placeholder: "Enter year" %>
    <% if year_was_invalid %>
      <% quarter.errors.full_messages_for(:year).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/quarters/_list_item.html.erb
<%= link_to quarter, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= quarter %>
    <small class="text-muted">
      <%= time_ago_in_words(quarter.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/quarters/_quarter_course_offerings.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Course Offerings

    <a data-toggle="collapse" href="#quarter_course_offerings_new_form">
      Add course offering
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @quarter.course_offerings.each do |course_offering| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to course_offering, course_offering %>

        <%= link_to course_offering, method: :delete, data: { confirm: "Do you really want to delete this course_offering" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="quarter_course_offerings_new_form">
        <%= render partial: "quarters/quarter_course_offerings_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/quarters/_quarter_course_offerings_new_form.html.erb
<%= form_with(model: @course_offering, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :course_id %>

    <%= f.collection_select :course_id, Course.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :quarter_id, value: @quarter.id %>

  <div class="form-group">
    <%= f.label :prof_id %>

    <%= f.collection_select :prof_id, Professor.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.submit "Create course offering", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/quarters/_quarter_courses.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Courses
  </div>

  <ul class="list-group list-group-flush">
    <% @quarter.courses.each do |course| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/courses/<%= course.id %>">
          <%= course %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/quarters/_quarters_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "quarters_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :season_cont, "Season contains" %>
    <%= f.text_field :season_cont, :class => "form-control", :placeholder => "Season contains" %>
  </div>

  <div class="form-group">
    <%= f.label :year, "Year" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :year_gteq, :class => "form-control", :placeholder => "Year greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :year_lteq, :class => "form-control", :placeholder => "Year less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :courses_course_number_cont, "Courses course_number contains" %>
    <%= f.text_field :courses_course_number_cont, :class => "form-control", :placeholder => "Courses course_number contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/quarters" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#quarters_filters">
  Show filters
</a>

app/views/quarters/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Quarter #<%= @quarter.id %>
      </h2>

      <div class="card-body">
        <%= render "form", quarter: @quarter %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/quarters/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Quarters

      <%= link_to new_quarter_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "quarters/quarters_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Quarters

        <%= link_to new_quarter_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @quarters, partial: "list_item", as: :quarter %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @quarters, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/quarters/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Quarter
      </h2>

      <div class="card-body">
        <%= render "form", quarter: @quarter %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/quarters/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @quarter, partial: "card", as: :quarter %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "quarters/quarter_course_offerings" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "quarters/quarter_courses" %>
  </div>
</div>