config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :user_needs

      resources :comments

      resources :course_ratings

      resources :quarters

      resources :course_offerings

      resources :professors

      resources :courses

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "courses#index"
  resources :user_needs
  resources :comments
  resources :course_ratings
  resources :quarters
  resources :course_offerings
  resources :professors
  resources :courses
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/course_rating.rb
class CourseRating < ApplicationRecord
  # Direct associations

  has_many   :comments,
             dependent: :destroy

  belongs_to :course_offering

  belongs_to :user

  # Indirect associations

  has_one    :prof,
             through: :course_offering,
             source: :prof

  # Validations

  # Scopes

  def to_s
    user.to_s
  end
end

app/controllers/api/v1/course_ratings_controller.rb
class Api::V1::CourseRatingsController < Api::V1::GraphitiController
  def index
    course_ratings = CourseRatingResource.all(params)
    respond_with(course_ratings)
  end

  def show
    course_rating = CourseRatingResource.find(params)
    respond_with(course_rating)
  end

  def create
    course_rating = CourseRatingResource.build(params)

    if course_rating.save
      render jsonapi: course_rating, status: :created
    else
      render jsonapi_errors: course_rating
    end
  end

  def update
    course_rating = CourseRatingResource.find(params)

    if course_rating.update_attributes
      render jsonapi: course_rating
    else
      render jsonapi_errors: course_rating
    end
  end

  def destroy
    course_rating = CourseRatingResource.find(params)

    if course_rating.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: course_rating
    end
  end
end

app/controllers/course_ratings_controller.rb
class CourseRatingsController < ApplicationController
  before_action :current_user_must_be_course_rating_user,
                only: %i[edit update destroy]

  before_action :set_course_rating, only: %i[show edit update destroy]

  def index
    @q = CourseRating.ransack(params[:q])
    @course_ratings = @q.result(distinct: true).includes(:user,
                                                         :course_offering, :comments, :prof).page(params[:page]).per(10)
  end

  def show
    @comment = Comment.new
  end

  def new
    @course_rating = CourseRating.new
  end

  def edit; end

  def create
    @course_rating = CourseRating.new(course_rating_params)

    if @course_rating.save
      message = "CourseRating was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @course_rating, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @course_rating.update(course_rating_params)
      redirect_to @course_rating,
                  notice: "Course rating was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @course_rating.destroy
    message = "CourseRating was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to course_ratings_url, notice: message
    end
  end

  private

  def current_user_must_be_course_rating_user
    set_course_rating
    unless current_user == @course_rating.user
      redirect_back fallback_location: root_path,
                    alert: "You are not authorized for that."
    end
  end

  def set_course_rating
    @course_rating = CourseRating.find(params[:id])
  end

  def course_rating_params
    params.require(:course_rating).permit(:user_id, :facet_1_rating,
                                          :facet_2_rating, :facet_3_rating, :facet_4_rating, :facet_5_rating, :descriptive_q1, :descriptive_q2, :descriptive_q3, :course_offering_id)
  end
end

app/views/course_ratings/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Course Rating #<%= course_rating.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>User</dt>
      <dd>
        <% if @course_rating.user.present? %>
          <%= link_to course_rating.user, course_rating.user %>
        <% end %>
      </dd>

      <dt>Facet 1 rating</dt>
      <dd><%= course_rating.facet_1_rating %></dd>

      <dt>Facet 2 rating</dt>
      <dd><%= course_rating.facet_2_rating %></dd>

      <dt>Facet 3 rating</dt>
      <dd><%= course_rating.facet_3_rating %></dd>

      <dt>Facet 4 rating</dt>
      <dd><%= course_rating.facet_4_rating %></dd>

      <dt>Facet 5 rating</dt>
      <dd><%= course_rating.facet_5_rating %></dd>

      <dt>Descriptive q1</dt>
      <dd><%= course_rating.descriptive_q1 %></dd>

      <dt>Descriptive q2</dt>
      <dd><%= course_rating.descriptive_q2 %></dd>

      <dt>Descriptive q3</dt>
      <dd><%= course_rating.descriptive_q3 %></dd>

      <dt>Course offering</dt>
      <dd>
        <% if @course_rating.course_offering.present? %>
          <%= link_to course_rating.course_offering, course_rating.course_offering %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back course_rating, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <% if current_user == @course_rating.user %>
          <%= link_to edit_course_rating_url(course_rating), class: "btn btn-block btn-sm btn-outline-secondary" do %>
            <i class="fas fa-edit"></i>
          <% end %>
        <% end %>
      </div>

      <div class="col">
        <% if current_user == @course_rating.user %>
          <%= link_to course_rating, method: :delete, data: { confirm: "Do you really want to delete this course_rating?" }, class: "btn btn-block btn-outline-secondary" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(course_rating.updated_at) %> ago
  </div>
</div>

app/views/course_ratings/_course_rating_comments.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Comments

    <a data-toggle="collapse" href="#course_rating_comments_new_form">
      Add comment
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @course_rating.comments.each do |comment| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to comment, comment %>

        <%= link_to comment, method: :delete, data: { confirm: "Do you really want to delete this comment" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="course_rating_comments_new_form">
        <%= render partial: "course_ratings/course_rating_comments_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/course_ratings/_course_rating_comments_new_form.html.erb
<%= form_with(model: @comment, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :user_id %>

    <%= f.collection_select :user_id, User.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :course_rating_id, value: @course_rating.id %>

  <%= f.submit "Create comment", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/course_ratings/_course_rating_prof.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Prof
  </div>

  <ul class="list-group list-group-flush">
    <% @course_rating.prof.each do |professor| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/professors/<%= professor.id %>">
          <%= professor %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/course_ratings/_course_ratings_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "course_ratings_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :descriptive_q3_cont, "Descriptive q3 contains" %>
    <%= f.text_field :descriptive_q3_cont, :class => "form-control", :placeholder => "Descriptive q3 contains" %>
  </div>

  <div class="form-group">
    <%= f.label :descriptive_q2_cont, "Descriptive q2 contains" %>
    <%= f.text_field :descriptive_q2_cont, :class => "form-control", :placeholder => "Descriptive q2 contains" %>
  </div>

  <div class="form-group">
    <%= f.label :descriptive_q1_cont, "Descriptive q1 contains" %>
    <%= f.text_field :descriptive_q1_cont, :class => "form-control", :placeholder => "Descriptive q1 contains" %>
  </div>

  <div class="form-group">
    <%= f.label :facet_5_rating, "Facet 5 rating" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :facet_5_rating_gteq, :class => "form-control", :placeholder => "Facet 5 rating greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :facet_5_rating_lteq, :class => "form-control", :placeholder => "Facet 5 rating less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :facet_4_rating, "Facet 4 rating" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :facet_4_rating_gteq, :class => "form-control", :placeholder => "Facet 4 rating greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :facet_4_rating_lteq, :class => "form-control", :placeholder => "Facet 4 rating less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :facet_3_rating, "Facet 3 rating" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :facet_3_rating_gteq, :class => "form-control", :placeholder => "Facet 3 rating greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :facet_3_rating_lteq, :class => "form-control", :placeholder => "Facet 3 rating less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :facet_2_rating, "Facet 2 rating" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :facet_2_rating_gteq, :class => "form-control", :placeholder => "Facet 2 rating greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :facet_2_rating_lteq, :class => "form-control", :placeholder => "Facet 2 rating less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :facet_1_rating, "Facet 1 rating" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :facet_1_rating_gteq, :class => "form-control", :placeholder => "Facet 1 rating greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :facet_1_rating_lteq, :class => "form-control", :placeholder => "Facet 1 rating less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :user_email_cont, "User email contains" %>
    <%= f.text_field :user_email_cont, :class => "form-control", :placeholder => "User email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :prof_prof_first_name_cont, "Prof prof_first_name contains" %>
    <%= f.text_field :prof_prof_first_name_cont, :class => "form-control", :placeholder => "Prof prof_first_name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/course_ratings" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#course_ratings_filters">
  Show filters
</a>

app/views/course_ratings/_form.html.erb
<% was_validated = course_rating.errors.any? %>

<%= form_with(model: course_rating, local: true, novalidate: true, class: "mb-3") do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="form-group">
    <% facet_1_rating_class = "form-control" %>
    <% facet_1_rating_was_invalid = course_rating.errors.include?(:facet_1_rating) %>

    <% if was_validated %>
      <% if facet_1_rating_was_invalid %>
        <% facet_1_rating_class << " is-invalid" %>
      <% else %>
        <% facet_1_rating_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :facet_1_rating %>
    <%= f.number_field :facet_1_rating, class: facet_1_rating_class, placeholder: "Enter facet 1 rating" %>
    <% if facet_1_rating_was_invalid %>
      <% course_rating.errors.full_messages_for(:facet_1_rating).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% facet_2_rating_class = "form-control" %>
    <% facet_2_rating_was_invalid = course_rating.errors.include?(:facet_2_rating) %>

    <% if was_validated %>
      <% if facet_2_rating_was_invalid %>
        <% facet_2_rating_class << " is-invalid" %>
      <% else %>
        <% facet_2_rating_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :facet_2_rating %>
    <%= f.number_field :facet_2_rating, class: facet_2_rating_class, placeholder: "Enter facet 2 rating" %>
    <% if facet_2_rating_was_invalid %>
      <% course_rating.errors.full_messages_for(:facet_2_rating).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% facet_3_rating_class = "form-control" %>
    <% facet_3_rating_was_invalid = course_rating.errors.include?(:facet_3_rating) %>

    <% if was_validated %>
      <% if facet_3_rating_was_invalid %>
        <% facet_3_rating_class << " is-invalid" %>
      <% else %>
        <% facet_3_rating_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :facet_3_rating %>
    <%= f.number_field :facet_3_rating, class: facet_3_rating_class, placeholder: "Enter facet 3 rating" %>
    <% if facet_3_rating_was_invalid %>
      <% course_rating.errors.full_messages_for(:facet_3_rating).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% facet_4_rating_class = "form-control" %>
    <% facet_4_rating_was_invalid = course_rating.errors.include?(:facet_4_rating) %>

    <% if was_validated %>
      <% if facet_4_rating_was_invalid %>
        <% facet_4_rating_class << " is-invalid" %>
      <% else %>
        <% facet_4_rating_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :facet_4_rating %>
    <%= f.number_field :facet_4_rating, class: facet_4_rating_class, placeholder: "Enter facet 4 rating" %>
    <% if facet_4_rating_was_invalid %>
      <% course_rating.errors.full_messages_for(:facet_4_rating).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% facet_5_rating_class = "form-control" %>
    <% facet_5_rating_was_invalid = course_rating.errors.include?(:facet_5_rating) %>

    <% if was_validated %>
      <% if facet_5_rating_was_invalid %>
        <% facet_5_rating_class << " is-invalid" %>
      <% else %>
        <% facet_5_rating_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :facet_5_rating %>
    <%= f.number_field :facet_5_rating, class: facet_5_rating_class, placeholder: "Enter facet 5 rating" %>
    <% if facet_5_rating_was_invalid %>
      <% course_rating.errors.full_messages_for(:facet_5_rating).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% descriptive_q1_class = "form-control" %>
    <% descriptive_q1_was_invalid = course_rating.errors.include?(:descriptive_q1) %>

    <% if was_validated %>
      <% if descriptive_q1_was_invalid %>
        <% descriptive_q1_class << " is-invalid" %>
      <% else %>
        <% descriptive_q1_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :descriptive_q1 %>
    <%= f.text_field :descriptive_q1, class: descriptive_q1_class, placeholder: "Enter descriptive q1" %>
    <% if descriptive_q1_was_invalid %>
      <% course_rating.errors.full_messages_for(:descriptive_q1).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% descriptive_q2_class = "form-control" %>
    <% descriptive_q2_was_invalid = course_rating.errors.include?(:descriptive_q2) %>

    <% if was_validated %>
      <% if descriptive_q2_was_invalid %>
        <% descriptive_q2_class << " is-invalid" %>
      <% else %>
        <% descriptive_q2_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :descriptive_q2 %>
    <%= f.text_field :descriptive_q2, class: descriptive_q2_class, placeholder: "Enter descriptive q2" %>
    <% if descriptive_q2_was_invalid %>
      <% course_rating.errors.full_messages_for(:descriptive_q2).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% descriptive_q3_class = "form-control" %>
    <% descriptive_q3_was_invalid = course_rating.errors.include?(:descriptive_q3) %>

    <% if was_validated %>
      <% if descriptive_q3_was_invalid %>
        <% descriptive_q3_class << " is-invalid" %>
      <% else %>
        <% descriptive_q3_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :descriptive_q3 %>
    <%= f.text_field :descriptive_q3, class: descriptive_q3_class, placeholder: "Enter descriptive q3" %>
    <% if descriptive_q3_was_invalid %>
      <% course_rating.errors.full_messages_for(:descriptive_q3).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% course_offering_class = "form-control" %>
    <% course_offering_was_invalid = course_rating.errors.include?(:course_offering) %>

    <% if was_validated %>
      <% if course_offering_was_invalid %>
        <% course_offering_class << " is-invalid" %>
      <% else %>
        <% course_offering_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :course_offering_id %>
    <%= f.collection_select :course_offering_id, CourseOffering.all, :id, :to_s, {}, class: "form-control" %>
    <% if course_offering_was_invalid %>
      <% course_rating.errors.full_messages_for(:course_offering).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/course_ratings/_list_item.html.erb
<%= link_to course_rating, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= course_rating %>
    <small class="text-muted">
      <%= time_ago_in_words(course_rating.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/course_ratings/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Course Rating #<%= @course_rating.id %>
      </h2>

      <div class="card-body">
        <%= render "form", course_rating: @course_rating %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/course_ratings/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Course Ratings

      <%= link_to new_course_rating_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "course_ratings/course_ratings_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Course Ratings

        <%= link_to new_course_rating_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @course_ratings, partial: "list_item", as: :course_rating %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @course_ratings, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/course_ratings/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Course Rating
      </h2>

      <div class="card-body">
        <%= render "form", course_rating: @course_rating %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/course_ratings/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @course_rating, partial: "card", as: :course_rating %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "course_ratings/course_rating_comments" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "course_ratings/course_rating_prof" %>
  </div>
</div>