config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :user_needs

      resources :comments

      resources :course_ratings

      resources :quarters

      resources :course_offerings

      resources :professors

      resources :courses

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "courses#index"
  resources :user_needs
  resources :comments
  resources :course_ratings
  resources :quarters
  resources :course_offerings
  resources :professors
  resources :courses
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/api/v1/courses_controller.rb
class Api::V1::CoursesController < Api::V1::GraphitiController
  def index
    courses = CourseResource.all(params)
    respond_with(courses)
  end

  def show
    course = CourseResource.find(params)
    respond_with(course)
  end

  def create
    course = CourseResource.build(params)

    if course.save
      render jsonapi: course, status: :created
    else
      render jsonapi_errors: course
    end
  end

  def update
    course = CourseResource.find(params)

    if course.update_attributes
      render jsonapi: course
    else
      render jsonapi_errors: course
    end
  end

  def destroy
    course = CourseResource.find(params)

    if course.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: course
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[show edit update destroy]

  def index
    @q = Course.ransack(params[:q])
    @courses = @q.result(distinct: true).includes(:course_offerings,
                                                  :quarters, :proves).page(params[:page]).per(10)
  end

  def show
    @course_offering = CourseOffering.new
  end

  def new
    @course = Course.new
  end

  def edit; end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to @course, notice: "Course was successfully created."
    else
      render :new
    end
  end

  def update
    if @course.update(course_params)
      redirect_to @course, notice: "Course was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @course.destroy
    redirect_to courses_url, notice: "Course was successfully destroyed."
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:course_number, :course_name,
                                   :course_description)
  end
end

app/views/courses/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Course #<%= course.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Course number</dt>
      <dd><%= course.course_number %></dd>

      <dt>Course name</dt>
      <dd><%= course.course_name %></dd>

      <dt>Course description</dt>
      <dd><%= course.course_description %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back course, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_course_url(course), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to course, method: :delete, data: { confirm: "Do you really want to delete this course?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(course.updated_at) %> ago
  </div>
</div>

app/views/courses/_course_course_offerings.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Course Offerings

    <a data-toggle="collapse" href="#course_course_offerings_new_form">
      Add course offering
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @course.course_offerings.each do |course_offering| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to course_offering, course_offering %>

        <%= link_to course_offering, method: :delete, data: { confirm: "Do you really want to delete this course_offering" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="course_course_offerings_new_form">
        <%= render partial: "courses/course_course_offerings_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/courses/_course_course_offerings_new_form.html.erb
<%= form_with(model: @course_offering, local: true) do |f| %>

  <%= f.hidden_field :course_id, value: @course.id %>

  <div class="form-group">
    <%= f.label :quarter_id %>

    <%= f.collection_select :quarter_id, Quarter.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :prof_id %>

    <%= f.collection_select :prof_id, Professor.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.submit "Create course offering", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/courses/_course_proves.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Proves
  </div>

  <ul class="list-group list-group-flush">
    <% @course.proves.each do |professor| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/professors/<%= professor.id %>">
          <%= professor %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/courses/_course_quarters.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Quarters
  </div>

  <ul class="list-group list-group-flush">
    <% @course.quarters.each do |quarter| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/quarters/<%= quarter.id %>">
          <%= quarter %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/courses/_courses_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "courses_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :course_number_cont, "Course number contains" %>
    <%= f.text_field :course_number_cont, :class => "form-control", :placeholder => "Course number contains" %>
  </div>

  <div class="form-group">
    <%= f.label :course_description_cont, "Course description contains" %>
    <%= f.text_field :course_description_cont, :class => "form-control", :placeholder => "Course description contains" %>
  </div>

  <div class="form-group">
    <%= f.label :course_name_cont, "Course name contains" %>
    <%= f.text_field :course_name_cont, :class => "form-control", :placeholder => "Course name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :quarters_season_cont, "Quarters season contains" %>
    <%= f.text_field :quarters_season_cont, :class => "form-control", :placeholder => "Quarters season contains" %>
  </div>

  <div class="form-group">
    <%= f.label :proves_prof_first_name_cont, "Proves prof_first_name contains" %>
    <%= f.text_field :proves_prof_first_name_cont, :class => "form-control", :placeholder => "Proves prof_first_name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/courses" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#courses_filters">
  Show filters
</a>

app/views/courses/_form.html.erb
<% was_validated = course.errors.any? %>

<%= form_with(model: course, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% course_number_class = "form-control" %>
    <% course_number_was_invalid = course.errors.include?(:course_number) %>

    <% if was_validated %>
      <% if course_number_was_invalid %>
        <% course_number_class << " is-invalid" %>
      <% else %>
        <% course_number_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :course_number %>
    <%= f.text_field :course_number, class: course_number_class, placeholder: "Enter course number" %>
    <% if course_number_was_invalid %>
      <% course.errors.full_messages_for(:course_number).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% course_name_class = "form-control" %>
    <% course_name_was_invalid = course.errors.include?(:course_name) %>

    <% if was_validated %>
      <% if course_name_was_invalid %>
        <% course_name_class << " is-invalid" %>
      <% else %>
        <% course_name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :course_name %>
    <%= f.text_field :course_name, class: course_name_class, placeholder: "Enter course name" %>
    <% if course_name_was_invalid %>
      <% course.errors.full_messages_for(:course_name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% course_description_class = "form-control" %>
    <% course_description_was_invalid = course.errors.include?(:course_description) %>

    <% if was_validated %>
      <% if course_description_was_invalid %>
        <% course_description_class << " is-invalid" %>
      <% else %>
        <% course_description_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :course_description %>
    <%= f.text_field :course_description, class: course_description_class, placeholder: "Enter course description" %>
    <% if course_description_was_invalid %>
      <% course.errors.full_messages_for(:course_description).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/courses/_list_item.html.erb
<%= link_to course, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= course %>
    <small class="text-muted">
      <%= time_ago_in_words(course.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/courses/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Course #<%= @course.id %>
      </h2>

      <div class="card-body">
        <%= render "form", course: @course %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/courses/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Courses

      <%= link_to new_course_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "courses/courses_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Courses

        <%= link_to new_course_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @courses, partial: "list_item", as: :course %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @courses, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/courses/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Course
      </h2>

      <div class="card-body">
        <%= render "form", course: @course %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/courses/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @course, partial: "card", as: :course %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "courses/course_course_offerings" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "courses/course_quarters" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "courses/course_proves" %>
  </div>
</div>